server:
  port: 8763
  context-path: /message
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: message
  activemq:
    broker-url: tcp://localhost:61616
    in-memory: true
    pool:
      enabled: false
  mail:
    #host: smtp.126.com
    #username: abc110110123@126.com
    #password: 110110110jyp
    host: smtp.qq.com
    #mailPort=465
    port: 587
    username: jyp.beijing@qq.com
    password: bwzbsobchzpabdaf
    default-encoding: UTF-8
    enable: true
    smtp: 
      auth: true
    starttls:
      enable: true
      required: true
########################################

msg: 
  subject: 标题注册成功
  text: 邮件内容：恭喜{}用户注册成功！
